version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: liverelay_postgres
    environment:
      POSTGRES_USER: uncledev
      POSTGRES_PASSWORD: liverelay_postgres25
      POSTGRES_DB: liverelay
    ports:
      - '5436:5432' # Host Port : Container Port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U uncledev']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
